version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    volumes:
      - .:/app
    command: ["npm", "start"]

  nginx:
    restart: always
    image: nginx:latest
    expose:
      - 8080
      - 443
    ports:
      - "80:8080"
      - "443:443"
    depends_on:
      - app